### PR TITLE
[WIP]: Fixes #45835

### PR DESCRIPTION
**Pull request by rajgoesout**
[WIP]: Fixes https://trac.macports.org/ticket/45835

I made an attempt to build on xcode 11.4.1.
It seems to build successfully, but there is an issue at runtime. 
This is the error message: `Pallet[18124:379385] [Pallet] initialize:1064: *** invalid JPEG2000 file`
full log: https://paste.macports.org/7f8becc66dcf

The debugger is pausing at [this line](https://github.com/macports/pallet/blob/master/MacPorts_Framework/MPInterpreter.m#L393)
Here's a screenshot: 
Screenshot 2020-05-05 at 5 50 19 PM

It seems that jpeg2000 decoding is broken: https://forums.developer.apple.com/thread/68444

Can someone provide some feedback?

**PS.** I'm a noob in objective c

### CODE REVIEW

**Comment by raimue** [comment]
These are separate issues. Apparently, the JPEG2000 cannot be parsed, but this appears to be just a warning and the startup continues. I would assume this is about the icons used for the menus etc.

What you see there in the debugger is a NULL-pointer dereference. Check all parameters that are passed into this function.

**Comment by rajgoesout** [comment]
Thanks @raimue, a null pointer was dereferenced due to an API change (I had to pass `nonewline` as an argument to `ui_message` to fix this). Pallet is now running, but there are several issues. For example, I am not able see the list of installed ports (it is getting printed on the console though). I have temporarily commented out [lines 39 and 48](https://github.com/macports/pallet/pull/1/commits/596ff92111661d8330ad269bb10049b29e5fcbbd#diff-5ac71232630dc985062a348079a25650R39) because they were causing exceptions: 
`Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread`
and also 
`NSWindow drag regions should only be invalidated on the Main Thread`

Sorry to bother you.

**Comment by kencu** [comment]
it's alive!! (Built on Xcode 4.6, macOS 10.7, the "nonewline" fix from here, and a few other tweaks). I did not use all of this PR, btw.

Screen Shot 2021-01-06 at 5 57 37 PM

**Comment by mascguy** [comment]
Looking forward to trying it!

**Comment by mojca** [comment]
I just wanted to express my big gratitude for the work you did. I just don't feel competent to do a code review as I have never written more than a few lines of Objective C code. I guess that @kencu should be able to provide sufficient feedback to lead to the merge of the code. Thanks a lot to everyone involved.

**Comment by mojca** [comment]
Maybe @juanger who made some substantial contributions would still be willing to review the code?

**Comment by rajgoesout** [comment]
@kencu Thanks! Could you perhaps create a new PR, and close this one? I haven't touched this in a long time and don't have the bandwidth to update the code at the moment.

**Comment by kencu** [comment]
sure, thanks for the inspiration

**Comment by mascguy** [comment]
Folks, how much work is left? I ask, as depending on the scope, I might be willing to take this on. (Particularly if the work is no more than a full day or two, max.)

**Comment by kencu** [comment]
At this moment, Pallet is communicating with the MPFramework sufficiently to return the list of installed ports, and Pallet can sort and select them, show info, etc.

But communicating with the MPFramework and specifically the helper tool is not doing any higher level functions (like sync, install, uninstall, etc) -- basically all the ones that would need sudo it appears. 

So that is how far I have it to this point. <https://github.com/kencu/pallet/tree/ken_10_7_build>

**Comment by mascguy** [comment]
Sounds good... I'll fork your repo, and take a look.

**Comment by kencu** [comment]
BTW -- at this moment, the optimal system for development for me seems to be 10.9. Systems that are too new error out with issues about the UI being updated from a background thread. The code is at present written to 10.8+ system requirements and will quickly generate an error on earlier systems.

I didn't try 10.10 through 10.13 yet to see if they work.

**Comment by mascguy** [comment]
Good to know, I'll start with 10.9 then.

**Comment by mascguy** [comment]
I finally started looking at this again last night. Can't believe it's been 18 days, the past two weeks have simply flown by!

Anyhow, my Mac development skills are rusty, but I'll get there.

**Comment by kencu** [comment]
a good first step to fixing it is to obtain Apple's BetterAuthorizationSample example that was used as the basis of this (the older version for now, not the newer version).

That runs without any trouble for me.

Next, figure out what has been broken at some point in Pallet to make the message passing from the main app to the worker app stop working.

**Pull request closed without merging**
